name: ThatCoolDad
favicon: null
layout_spectrum: 0.03478720993734896
typography_spectrum: 0.6163
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252a68'
    - '#c12026'
    - '#9a2237'
    - '#772447'
    - '#5f2651'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
